### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by MuaazOsaidTahir** [zaid4317/Crash-Course-on-Python-by-Google#2]
Thanks for your reply Zaahid.
Can you please help me doing the final project it is just going over my head

**Comment by zaahidali** [comment]
Dear Muaaz, 
It is a very simple project. Try to follow the instructions that they have provided and if you are still unable to solve it then rewatch the lectures or ask for help in the discussion forums or try to read other people's project code. I'm sure it will help you a lot in completing the project.
Thank you.
